dist: xenial
language: bash
sudo: required
addons:
  snaps:
  - name: snapcraft
    channel: stable
    confinement: classic
  - name: lxd
    channel: stable
  apt:
    packages:
    - python3
    - python3-pip
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
